set define off
-- DELETE FROM ua_plugin_info WHERE scriptName = 'dbsize.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','dbsize.py','数据库大小','db/mysql/dbsize.py','linux,windows','root','python','1528781864858','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/dbsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/dbsize.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/dbsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/dbsize.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/dbsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/dbsize.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/dbsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/dbsize.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'mysqlcheck.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','mysqlcheck.py','mysql数据库信息','db/mysql/mysqlcheck.py','linux,windows','root','python','1528781864880','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/mysqlcheck.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/mysqlcheck.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/mysqlcheck.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/mysqlcheck.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/mysqlcheck.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/mysqlcheck.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/mysqlcheck.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/mysqlcheck.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'connectionrate.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','connectionrate.py','线程的使用率','db/mysql/connectionrate.py','linux,windows','root','python','1528781864902','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrate.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrate.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrate.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrate.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'connectionrequestfailnum.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','connectionrequestfailnum.py','请求连接失败数','db/mysql/connectionrequestfailnum.py','linux,windows','root','python','1528781864928','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrequestfailnum.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrequestfailnum.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrequestfailnum.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrequestfailnum.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrequestfailnum.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrequestfailnum.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/connectionrequestfailnum.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/connectionrequestfailnum.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'currentactiveconnectionnumber.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','currentactiveconnectionnumber.py','当前活跃连接数','db/mysql/currentactiveconnectionnumber.py','linux,windows','root','python','1528781864953','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentactiveconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentactiveconnectionnumber.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentactiveconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentactiveconnectionnumber.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentactiveconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentactiveconnectionnumber.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentactiveconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentactiveconnectionnumber.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'currentconnectionnumber.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','currentconnectionnumber.py','当前打开的连接的数量','db/mysql/currentconnectionnumber.py','linux,windows','root','python','1528781864978','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentconnectionnumber.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentconnectionnumber.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentconnectionnumber.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/currentconnectionnumber.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/currentconnectionnumber.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'databaseindexused.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','databaseindexused.py','索引使用空间大小','db/mysql/databaseindexused.py','linux,windows','root','python','1528781865003','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databaseindexused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databaseindexused.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databaseindexused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databaseindexused.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databaseindexused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databaseindexused.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databaseindexused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databaseindexused.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'databasename.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','databasename.py','数据库名','db/mysql/databasename.py','linux,windows','root','python','1528781865029','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasename.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasename.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasename.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasename.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasename.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasename.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasename.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasename.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'databasespaceused.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','databasespaceused.py','已用数据库空间','db/mysql/databasespaceused.py','linux,windows','root','python','1528781865054','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasespaceused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasespaceused.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasespaceused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasespaceused.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasespaceused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasespaceused.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/databasespaceused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/databasespaceused.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'innodbpage.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','innodbpage.py','Innodb页大小','db/mysql/innodbpage.py','linux,windows','root','python','1528781865080','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpage.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpage.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpage.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpage.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpage.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpage.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpage.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpage.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'innodbpool.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','innodbpool.py','Innodb缓存池大小','db/mysql/innodbpool.py','linux,windows','root','python','1528781865107','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpool.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpool.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpool.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/innodbpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/innodbpool.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'maxconnections.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','maxconnections.py','服务器启动同时使用的最大数目连接数','db/mysql/maxconnections.py','linux,windows','root','python','1528781865135','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/maxconnections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/maxconnections.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/maxconnections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/maxconnections.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/maxconnections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/maxconnections.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/maxconnections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/maxconnections.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'max_connections.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','max_connections.py','最大允许连接数','db/mysql/max_connections.py','linux,windows','root','python','1528781865159','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/max_connections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/max_connections.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/max_connections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/max_connections.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/max_connections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/max_connections.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/max_connections.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/max_connections.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'nls.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','nls.py','字符集','db/mysql/nls.py','linux,windows','root','python','1528781865183','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/nls.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/nls.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/nls.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/nls.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/nls.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/nls.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/nls.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/nls.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'path.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','path.py','安装目录','db/mysql/path.py','linux,windows','root','python','1528781865207','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/path.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/path.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/path.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/path.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/path.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/path.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/path.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/path.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'querycachesize.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','querycachesize.py','查询缓存空间大小','db/mysql/querycachesize.py','linux,windows','root','python','1528781865232','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/querycachesize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/querycachesize.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/querycachesize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/querycachesize.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/querycachesize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/querycachesize.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/querycachesize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/querycachesize.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'version.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','version.py','数据库版本','db/mysql/version.py','linux,windows','root','python','1528781865254','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/version.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/version.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/version.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/version.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/version.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/version.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/version.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/version.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'writedatatimea.py' and SCRIPTPATH ='db/mysql';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResMysql','db/mysql','writedatatimea.py','写数据次数','db/mysql/writedatatimea.py','linux,windows','root','python','1528781865278','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/writedatatimea.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/writedatatimea.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/writedatatimea.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/writedatatimea.py','port','端口','varchar(50)','1-65536',0,0,'3306','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/writedatatimea.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/writedatatimea.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/mysql/writedatatimea.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/mysql/writedatatimea.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

commit;