set define off
-- DELETE FROM ua_plugin_info WHERE scriptName = 'lsnrstatus.sh' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','lsnrstatus.sh','监听状态','db/oracle/lsnrstatus.sh','linux','root','shell','1526363011937','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lsnrstatus.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lsnrstatus.sh','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lsnrstatus.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lsnrstatus.sh','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lsnrstatus.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lsnrstatus.sh','servername','数据库名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'sessused.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','sessused.py','数据库当前会话使用率','db/oracle/sessused.py','linux','root','python','1526363011973','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'buffhitratio.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','buffhitratio.py','数据块在数据缓冲区中的命中率','db/oracle/buffhitratio.py','linux','root','python','1526363012038','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffhitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffhitratio.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffhitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffhitratio.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffhitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffhitratio.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffhitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffhitratio.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffhitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffhitratio.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'tbspctused.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','tbspctused.py','表空间利用率','db/oracle/tbspctused.py','linux','root','python','1526363012094','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tbspctused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tbspctused.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tbspctused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tbspctused.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tbspctused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tbspctused.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tbspctused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tbspctused.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tbspctused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tbspctused.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'sgamaxsize.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','sgamaxsize.py','SGA大小','db/oracle/sgamaxsize.py','linux','root','python','1526363012133','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sgamaxsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sgamaxsize.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sgamaxsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sgamaxsize.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sgamaxsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sgamaxsize.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sgamaxsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sgamaxsize.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sgamaxsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sgamaxsize.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'logbuffer.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','logbuffer.py','日志缓冲区大小','db/oracle/logbuffer.py','linux','root','python','1526363012188','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/logbuffer.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/logbuffer.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/logbuffer.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/logbuffer.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/logbuffer.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/logbuffer.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/logbuffer.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/logbuffer.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/logbuffer.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/logbuffer.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'sharedpool.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','sharedpool.py','共享池大小','db/oracle/sharedpool.py','linux','root','python','1526363012236','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sharedpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sharedpool.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sharedpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sharedpool.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sharedpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sharedpool.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sharedpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sharedpool.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sharedpool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sharedpool.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'largepool.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','largepool.py','大池大小','db/oracle/largepool.py','linux','root','python','1526363012278','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/largepool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/largepool.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/largepool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/largepool.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/largepool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/largepool.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/largepool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/largepool.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/largepool.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/largepool.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'javapoolsize.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','javapoolsize.py','JAVA池大小','db/oracle/javapoolsize.py','linux','root','python','1526363012329','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/javapoolsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/javapoolsize.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/javapoolsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/javapoolsize.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/javapoolsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/javapoolsize.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/javapoolsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/javapoolsize.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/javapoolsize.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/javapoolsize.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'defaultbuffercache.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','defaultbuffercache.py','数据缓冲区大小','db/oracle/defaultbuffercache.py','linux','root','python','1526363012376','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/defaultbuffercache.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/defaultbuffercache.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/defaultbuffercache.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/defaultbuffercache.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/defaultbuffercache.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/defaultbuffercache.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/defaultbuffercache.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/defaultbuffercache.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/defaultbuffercache.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/defaultbuffercache.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'buffbusyrate.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','buffbusyrate.py','缓冲池繁忙率','db/oracle/buffbusyrate.py','linux','root','python','1526363012411','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffbusyrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffbusyrate.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffbusyrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffbusyrate.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffbusyrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffbusyrate.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffbusyrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffbusyrate.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/buffbusyrate.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/buffbusyrate.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'currentsessions.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','currentsessions.py','当前会话数','db/oracle/currentsessions.py','linux','root','python','1526363012446','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/currentsessions.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/currentsessions.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/currentsessions.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/currentsessions.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/currentsessions.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/currentsessions.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/currentsessions.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/currentsessions.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/currentsessions.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/currentsessions.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'disksortsratio.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','disksortsratio.py','磁盘排序比率','db/oracle/disksortsratio.py','linux','root','python','1526363012488','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/disksortsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/disksortsratio.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/disksortsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/disksortsratio.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/disksortsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/disksortsratio.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/disksortsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/disksortsratio.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/disksortsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/disksortsratio.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'hitratios.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','hitratios.py','命中率监控','db/oracle/hitratios.py','linux','root','python','1526363012524','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/hitratios.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/hitratios.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/hitratios.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/hitratios.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/hitratios.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/hitratios.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/hitratios.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/hitratios.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/hitratios.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/hitratios.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'locksused.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','locksused.py','锁利用率','db/oracle/locksused.py','linux','root','python','1526363012557','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/locksused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/locksused.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/locksused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/locksused.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/locksused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/locksused.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/locksused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/locksused.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/locksused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/locksused.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'lockwaitratio.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','lockwaitratio.py','锁请求等待比例','db/oracle/lockwaitratio.py','linux','root','python','1526363012595','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lockwaitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lockwaitratio.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lockwaitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lockwaitratio.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lockwaitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lockwaitratio.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lockwaitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lockwaitratio.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lockwaitratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lockwaitratio.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'longscanratio.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','longscanratio.py','全表扫描百分比','db/oracle/longscanratio.py','linux','root','python','1526363012633','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/longscanratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/longscanratio.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/longscanratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/longscanratio.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/longscanratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/longscanratio.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/longscanratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/longscanratio.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/longscanratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/longscanratio.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'processeratio.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','processeratio.py','Processes利用率','db/oracle/processeratio.py','linux','root','python','1526363012672','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/processeratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/processeratio.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/processeratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/processeratio.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/processeratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/processeratio.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/processeratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/processeratio.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/processeratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/processeratio.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'sessionsratio.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','sessionsratio.py','session会话数利用率','db/oracle/sessionsratio.py','linux','root','python','1526363012711','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessionsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessionsratio.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessionsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessionsratio.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessionsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessionsratio.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessionsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessionsratio.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessionsratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessionsratio.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'tablespace.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','tablespace.py','表空间监控','db/oracle/tablespace.py','linux','root','python','1526363012747','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tablespace.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tablespace.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tablespace.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tablespace.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tablespace.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tablespace.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tablespace.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tablespace.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tablespace.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tablespace.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'tranusedpercent.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','tranusedpercent.py','事务数利用率','db/oracle/tranusedpercent.py','linux','root','python','1526363012783','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tranusedpercent.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tranusedpercent.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tranusedpercent.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tranusedpercent.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tranusedpercent.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tranusedpercent.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tranusedpercent.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tranusedpercent.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/tranusedpercent.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/tranusedpercent.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'userrollbacksratio.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDBInstance','db/oracle','userrollbacksratio.py','回滚事务率','db/oracle/userrollbacksratio.py','linux','root','python','1526363012813','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/userrollbacksratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/userrollbacksratio.py','ip','IP地址','varchar(50)','',1,0,'','1','1',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/userrollbacksratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/userrollbacksratio.py','port','端口','varchar(50)','1-65536',0,0,'1521','2','2',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/userrollbacksratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/userrollbacksratio.py','userName','用户名','varchar(50)','',1,0,'','3','3',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/userrollbacksratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/userrollbacksratio.py','password','密码','varchar(50)','',1,1,'','4','4',''); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/userrollbacksratio.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/userrollbacksratio.py','servername','数据库名','varchar(50)','',1,0,'','5','5',''); 

commit;