insert into UA_PLUGIN_INFO (SCRIPTID, SCRIPTPATH, SCRIPTNAME, ADAPTOS, SCRIPTNOTE, CREATOR, SCRIPTTYPE, CREATERTIME, UPDATOR, UPDATETIME, ISFORMAT, MPOINTCLASS, EXE_STRING2, EXE_STRING3, PYTHONVERSION, APPID)
values ('postgresql.py', '/', 'Postgresql.py', 'linux', 'SQl语句', 'root', 'python', '1525247471200', null, '0', '1', 'ResPostgresql', null, null, null, 'global');

insert into UA_SCRIPT_PARAM (SCRIPTID, PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE, EXE_STRING1, EXE_STRING2, EXE_STRING3, ISMAIN, APPID)
values ('postgresql.py', 'hostip', '数据库IP', '字符型', null, '1', '0', null, '1', '1', null, null, null, null, null, 'global');

insert into UA_SCRIPT_PARAM (SCRIPTID, PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE, EXE_STRING1, EXE_STRING2, EXE_STRING3, ISMAIN, APPID)
values ('postgresql.py', 'port', 'postgresql端口', '字符型', '1-65536', '1', '0', '5432', '2', '2', null, null, null, null, null, 'global');

insert into UA_SCRIPT_PARAM (SCRIPTID, PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE, EXE_STRING1, EXE_STRING2, EXE_STRING3, ISMAIN, APPID)
values ('postgresql.py', 'username', '连接账号', '字符型', null, '1', '0', null, '3', '3', null, null, null, null, null, 'global');

insert into UA_SCRIPT_PARAM (SCRIPTID, PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE, EXE_STRING1, EXE_STRING2, EXE_STRING3, ISMAIN, APPID)
values ('postgresql.py', 'password', '账号密码', '字符型', null, '1', '1', null, '4', '4', null, null, null, null, null, 'global');

insert into UA_SCRIPT_PARAM (SCRIPTID, PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE, EXE_STRING1, EXE_STRING2, EXE_STRING3, ISMAIN, APPID)
values ('postgresql.py', 'servicename', '数据库名', '字符型', null, '1', '0', null, '5', '5', null, null, null, null, null, 'global');

insert into UA_SCRIPT_PARAM (SCRIPTID, PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE, EXE_STRING1, EXE_STRING2, EXE_STRING3, ISMAIN, APPID)
values ('postgresql.py', 'sql', 'SQL语句', '字符型', null, '1', '0', null, '6', '6', null, null, null, null, null, 'global');

commit;