set define off
-- DELETE FROM ua_plugin_info WHERE scriptName = 'databasestatus.sh' and SCRIPTPATH ='db/db2';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDB2','db/db2','databasestatus.sh','数据库状态','db/db2/databasestatus.sh','linux','','shell','1526535990265','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/db2/databasestatus.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/db2/databasestatus.sh','instance','','','','',0,'','1','1','db2的数据库名称'); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'appls_cur_cons.sh' and SCRIPTPATH ='db/db2';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResDB2','db/db2','appls_cur_cons.sh','注册的代理程序数','db/db2/appls_cur_cons.sh','linux','','shell','1526535990274','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/db2/appls_cur_cons.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/db2/appls_cur_cons.sh','instance','','','','',0,'','1','1','db2的数据库名称'); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'lsnrstatus.sh' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResOraInstance','db/oracle','lsnrstatus.sh','监听状态','db/oracle/lsnrstatus.sh','linux','','shell','1526535990279','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lsnrstatus.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lsnrstatus.sh','ip','','','','',0,'','1','1','数据库IP地址'); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lsnrstatus.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lsnrstatus.sh','port','','','','',0,'','2','2','数据库端口'); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/lsnrstatus.sh';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/lsnrstatus.sh','instance','','','','',0,'','3','3','oracle实例名SID'); 

-- DELETE FROM ua_plugin_info WHERE scriptName = 'sessused.py' and SCRIPTPATH ='db/oracle';
INSERT INTO ua_plugin_info(MPOINTCLASS, SCRIPTPATH, SCRIPTNAME, SCRIPTNOTE, SCRIPTID, ADAPTOS, CREATOR, scriptType, createrTime, updateTime, isFormat) VALUES ('ResOraInstance','db/oracle','sessused.py','数据库当前会话使用率','db/oracle/sessused.py','linux','','python','1526535990303','0','1');
-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','ip','','','','',0,'','1','1','数据库IP地址'); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','port','','','','',0,'','2','2','数据库端口'); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','user','','','','',0,'','3','3','数据库的查询用户'); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','password','','','','',1,'','4','4','数据库的查询用户密码'); 

-- DELETE FROM UA_SCRIPT_PARAM WHERE SCRIPTID = 'db/oracle/sessused.py';
INSERT INTO UA_SCRIPT_PARAM(SCRIPTID,PARAMETERNAME, PARAMETERDESCR, PARAMETERDATATYPE, PARAMETERDATASCOPE, ISREQUIRED, ISENCRYPTED, DEFAULTVALUE, EXECSEQUENCE, VIEWSEQUENCE, NOTE) VALUES ('db/oracle/sessused.py','instance','','','','',0,'','5','5','oracle实例名SID'); 

commit;